# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  den.aspects.pc.nixos = {
    config,
    lib,
    modulesPath,
    ...
  }: {
    imports = [(modulesPath + "/installer/scan/not-detected.nix")];
    boot = {
      initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "sd_mod"];
      initrd.kernelModules = [];
      kernelModules = ["kvm-amd"];
      extraModulePackages = [];
    };

    fileSystems = {
      "/" = {
        device = "/dev/disk/by-uuid/4fdb2b25-e5c7-4ffe-b82f-21806f5699bb";
        fsType = "ext4";
      };

      "/boot" = {
        device = "/dev/disk/by-uuid/7CF1-738B";
        fsType = "vfat";
        options = ["fmask=0077" "dmask=0077"];
      };

      "/home/jaydenv/Games" = {
        device = "/dev/disk/by-uuid/eee960b6-5bee-4593-a6e0-644e4d20bdbd";
        fsType = "ext4";
        options = [
          "users"
          "nofail"
          "exec"
        ];
      };
    };

    swapDevices = [{device = "/dev/disk/by-uuid/5fdceac4-5c96-46c9-9091-893cb86be1a3";}];

    networking.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
